### Auth | Register user - existing user | 409

POST {{host}}/api/auth
Content-Type: application/json

{
  "firstname": "Nhoj",
  "lastname": "Eod",
  "username": "neod",
  "password": "NhojEod001",
  "email": "nhojeod@gmail.com",
  "phonenumber": "589-654",
  "roles": [
    "Manager"
  ]
}

### Auth | Login user | 200

POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "neod",
  "password": "NhojEod001"
}

### Auth | Login user - invalid credentials | 401

POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "jdoe",
  "password": "NhojEod001"
}