### Root

GET {{host}}/api
Accept: application/vnd.nanotome.apiroot+json

### Organization | Get all organizations | 200

GET {{ host }}/api/orgs
Accept: application/json
Authorization: Bearer {{token}}

### Organization | Get all organizations | 401

GET {{ host }}/api/orgs
Accept: application/json

### Organization | Get organization | 200

GET {{ host }}/api/orgs/{{org_01_Id}}
Accept: application/json
Authorization: Bearer {{token}}

### Organization | Get organization | 404: NOT FOUND

GET {{ host }}/api/orgs/{{badOrgId}}
Accept: application/json
Authorization: Bearer {{token}}

### Organization | Create organization | 201

POST {{host}}/api/orgs
Content-Type: application/json

{
  "name": "Nanotome GmbH",
  "address": "1 Strasse Strasse, 12345 Berlin",
  "country": "Germany"
}

### Organization | Create organization with participants | 201

POST {{host}}/api/orgs
Content-Type: application/json

{
  "name": "Unternehmen GmbH",
  "address": "100 Strasse Strasse, 12345 Berlin",
  "country": "Germany",
  "employees": [
    {
      "name": "Joan Dane",
      "age": 25,
      "position": "Manager"
    },
    {
      "name": "John Miths",
      "age": 32,
      "position": "Administrative"
    }
  ]
}

### Organization | Create organization | 400: BAD REQUEST

POST {{host}}/api/orgs
Content-Type: application/json
Authorization: Bearer {{token}}

## PARTICIPANTS

### Participants | Get all participants | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/participants
Accept: application/json
Authorization: Bearer {{token}}

### Participants | Get all participants - Cached | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/participants
Accept: application/json
Authorization: Bearer {{token}}
Cache-Control: max-age=604800

### Participants | Get all participants - Paged | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/participants?pageNumber=2&pageSize=1
Accept: application/json
Authorization: Bearer {{token}}

### Participants | Get all participants - Search | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/participants?searchTerm=Oliver
Accept: application/json
Authorization: Bearer {{token}}

### Participants | Get all participants - Sort | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/participants?orderBy=name,age desc
Accept: application/json
Authorization: Bearer {{token}}

### Participants | Get all participants - Selected Fields | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/participants?fields=name
Accept: application/json
Authorization: Bearer {{token}}

### Participants | Get all participants - Selected Fields (XML) | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/participants?fields=name
Accept: application/xml
Authorization: Bearer {{token}}

### Participants | Get all participants - HATEOAS | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/participants
Accept: application/vnd.nanotome.hateoas+json
Authorization: Bearer {{token}}

### Participants | Get participant | 200

GET {{host}}/api/orgs/{{org_01_Id}}/participants/{{participant_01_Id}}
Accept: application/json
Authorization: Bearer {{token}}

### Participants | Create participant | 201

POST {{host}}/api/orgs/{{org_01_Id}}/participants
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Hanako Taro",
  "age": 20,
  "position": "Software Developer"
}

### Participants | Create participant | 422: UNPROCESSABLE ENTITY

POST {{host}}/api/orgs/{{org_01_Id}}/participants
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": null,
  "age": 20,
  "position": null
}

### Participants | Update participant | 204

PATCH {{host}}/api/orgs/{{org_01_Id}}/participants/{{participant_01_Id}}
Content-Type: application/json-patch+json
Authorization: Bearer {{token}}

[
  {
    "op": "replace",
    "path": "/age",
    "value": 19
  }
]

### Participants | Delete participant | 204

DELETE {{host}}/api/orgs/{{org_01_Id}}/participants/{{participant_02_Id}}
Accept: application/json
Authorization: Bearer {{token}}

## LEADERBOARDS

### Leaderboards | Get all leaderboards | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/leaderboards
Accept: application/json
Authorization: Bearer {{token}}

### leaderboards | Get all leaderboards - Cached | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/leaderboards
Accept: application/json
Cache-Control: max-age=604800

### leaderboards | Get all leaderboards - Paged | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/leaderboards?pageNumber=2&pageSize=1
Accept: application/json

### leaderboards | Get all leaderboards - Search | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/leaderboards?searchTerm=Oliver
Accept: application/json

### leaderboards | Get all leaderboards - Sort | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/leaderboards?orderBy=name desc
Accept: application/json

### leaderboards | Get all leaderboards - Selected Fields | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/leaderboards?fields=name
Accept: application/json

### leaderboards | Get all leaderboards - Selected Fields (XML) | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/leaderboards?fields=name
Accept: application/xml

### leaderboards | Get all leaderboards - HATEOAS | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/leaderboards
Accept: application/vnd.nanotome.hateoas+json

### leaderboards | Get leaderboard | 200

GET {{host}}/api/orgs/{{org_01_Id}}/leaderboards/{{leaderboard_01_Id}}
Accept: application/json

### leaderboards | Create leaderboard | 201

POST {{host}}/api/orgs/{{org_01_Id}}/leaderboards
Content-Type: application/json

{
  "name": "General Sales"
}

### leaderboards | Create leaderboard | 422: UNPROCESSABLE ENTITY

POST {{host}}/api/orgs/{{org_01_Id}}/leaderboards
Content-Type: application/json

{
  "name": null
}

### leaderboards | Update leaderboard | 204

PATCH {{host}}/api/orgs/{{org_01_Id}}/leaderboards/{{leaderboard_02_Id}}
Content-Type: application/json-patch+json

[
  {
    "op": "replace",
    "path": "/name",
    "value": "new ranking"
  }
]

### leaderboards | Delete leaderboard | 204

DELETE {{host}}/api/orgs/{{org_01_Id}}/leaderboards/{{leaderboard_02_Id}}
Accept: application/json