### Participants | Get all scores | 200
### login, get the token then make the query

GET {{ host }}/api/participants/{{participant_01_Id}}scores
Accept: application/json
Authorization: Bearer {{token}}

### Participants | Get all leaderboards | 200
### login, get the token then make the query

GET {{ host }}/api/participants/{{participant_01_Id}}leaderboards
Accept: application/json
Authorization: Bearer {{token}}

