### Organization | Get all organizations | 200

GET {{ host }}/api/orgs
Accept: application/json

### Organization | Get organization | 404: NOT FOUND

GET {{ host }}/api/orgs/{{badOrgId}}
Accept: application/json

### Organization | Create organization | 201

POST {{host}}/api/orgs
Content-Type: application/json

{
  "name": "Nanotome GmbH",
  "address": "1 Strasse Strasse, 12345 Berlin",
  "country": "Germany"
}

### Organization | Create organization with participants | 201

POST {{host}}/api/orgs
Content-Type: application/json

{
  "name": "Unternehmen GmbH",
  "address": "100 Strasse Strasse, 12345 Berlin",
  "country": "Germany",
  "employees": [
    {
      "name": "Joan Dane",
      "age": 25,
      "position": "Manager"
    },
    {
      "name": "John Miths",
      "age": 32,
      "position": "Administrative"
    }
  ]
}

### Organization | Create organization | 400: BAD REQUEST

POST {{host}}/api/orgs
Content-Type: application/json

### Participants | Get all participants | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/participants
Accept: application/json

### Participants | Get all participants - Paged | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/participants?pageNumber=2&pageSize=1
Accept: application/json

### Participants | Get all participants - Search | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/participants?searchTerm=Oliver
Accept: application/json

### Participants | Get all participants - Sort | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/participants?orderBy=name,age desc
Accept: application/json

### Participants | Get all participants - Selected Fields | 200

GET {{ host }}/api/orgs/{{ org_01_Id}}/participants?fields=name
Accept: application/json

### Participants | Get participant | 200

GET {{host}}/api/orgs/{{org_01_Id}}/participants/{{participant_01_Id}}
Accept: application/json

### Participants | Create participant | 201

POST {{host}}/api/orgs/{{org_01_Id}}/participants
Content-Type: application/json

{
  "name": "Hanako Taro",
  "age": 20,
  "position": "Software Developer"
}

### Participants | Create participant | 422: UNPROCESSABLE ENTITY

POST {{host}}/api/orgs/{{org_01_Id}}/participants
Content-Type: application/json

{
  "name": null,
  "age": 20,
  "position": null
}

### Participants | Update participant | 204

PATCH {{host}}/api/orgs/{{org_01_Id}}/participants/{{participant_01_Id}}
Content-Type: application/json-patch+json

[
  {
    "op": "remove",
    "path": "/ageeeeee"
  }
]

### Participants | Delete participant | 204

DELETE {{host}}/api/orgs/{{org_01_Id}}/participants/{{participant_01_Id}}
Accept: application/json

