### Organization | Get all organizations

GET {{ host }}/api/organizations
Accept: application/json

### Organization | Get organization | not found

GET {{ host }}/api/Organizations/{{badOrgId}}
Accept: application/json

### Participants | Get all participants

GET {{ host }}/api/organizations/{{ org_01_Id}}/participants
Accept: application/json
