### Score | Get all scores | 200
### login, get the token then make the query

GET {{ host }}/api/scores
Accept: application/json
Authorization: Bearer {{token}}

### Score | Get score | 200
### todo: create two scores before testing get, update and delete routes

GET {{ host }}/api/scores/{{score_01_Id}}
Accept: application/json
Authorization: Bearer {{token}}

### Score | Create score | 201

POST {{host}}/api/scores
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "JsonValue": "{\"First\":100,\"Second\":50}",
  "leaderboardId": "a478da4c-a47b-4d95-896f-06368e844232",
  "participantId": "42829FE2-FB6C-4D53-B3FE-08DCD3674A21"
}

### Score | Update score | 204

PUT {{host}}/api/scores/{{score_01_Id}}
Content-Type: application/json-patch+json
Authorization: Bearer {{token}}

{
  "JsonValue": "{'First':2,'Second':4}"
}

### Scores | Delete score | 204

DELETE {{host}}/api/scores/{{score_02_Id}}
Accept: application/json
Authorization: Bearer {{token}}